# Generated by Django 4.1.6 on 2023-02-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyslexia',
            name='image',
            field=models.ImageField(default='/', upload_to='images/'),
            preserve_default=False,
        ),
    ]
